# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MejoresPuntajes.ui'
#
# Created: Fri Jul 19 18:49:54 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Puntajes(object):
    def setupUi(self, Puntajes):
        Puntajes.setObjectName(_fromUtf8("Puntajes"))
        Puntajes.resize(301, 347)
        self.tab = QtGui.QTabWidget(Puntajes)
        self.tab.setGeometry(QtCore.QRect(20, 60, 251, 231))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabPrincipiante = QtGui.QWidget()
        self.tabPrincipiante.setObjectName(_fromUtf8("tabPrincipiante"))
        self.tablePrincipiante = QtGui.QTableWidget(self.tabPrincipiante)
        self.tablePrincipiante.setGeometry(QtCore.QRect(10, 10, 221, 181))
        self.tablePrincipiante.setAutoScroll(False)
        self.tablePrincipiante.setObjectName(_fromUtf8("tablePrincipiante"))
        self.tablePrincipiante.setColumnCount(2)
        self.tablePrincipiante.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabPrincipiante, _fromUtf8(""))
        self.tabIntermedio = QtGui.QWidget()
        self.tabIntermedio.setObjectName(_fromUtf8("tabIntermedio"))
        self.tablePrincipiante_4 = QtGui.QTableWidget(self.tabIntermedio)
        self.tablePrincipiante_4.setGeometry(QtCore.QRect(10, 10, 221, 181))
        self.tablePrincipiante_4.setAutoScroll(False)
        self.tablePrincipiante_4.setObjectName(_fromUtf8("tablePrincipiante_4"))
        self.tablePrincipiante_4.setColumnCount(2)
        self.tablePrincipiante_4.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_4.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabIntermedio, _fromUtf8(""))
        self.tabAvanzado = QtGui.QWidget()
        self.tabAvanzado.setObjectName(_fromUtf8("tabAvanzado"))
        self.tablePrincipiante_2 = QtGui.QTableWidget(self.tabAvanzado)
        self.tablePrincipiante_2.setGeometry(QtCore.QRect(10, 10, 221, 181))
        self.tablePrincipiante_2.setAutoScroll(False)
        self.tablePrincipiante_2.setObjectName(_fromUtf8("tablePrincipiante_2"))
        self.tablePrincipiante_2.setColumnCount(2)
        self.tablePrincipiante_2.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante_2.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabAvanzado, _fromUtf8(""))
        self.btnSalir = QtGui.QPushButton(Puntajes)
        self.btnSalir.setGeometry(QtCore.QRect(120, 310, 75, 23))
        self.btnSalir.setObjectName(_fromUtf8("btnSalir"))
        self.labelMejoresTiempos = QtGui.QLabel(Puntajes)
        self.labelMejoresTiempos.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.labelMejoresTiempos.setStyleSheet(_fromUtf8("font: 75 20pt \"Broadway\";"))
        self.labelMejoresTiempos.setObjectName(_fromUtf8("labelMejoresTiempos"))

        self.retranslateUi(Puntajes)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Puntajes)

    def retranslateUi(self, Puntajes):
        Puntajes.setWindowTitle(_translate("Puntajes", "Dialog", None))
        item = self.tablePrincipiante.verticalHeaderItem(0)
        item.setText(_translate("Puntajes", "1", None))
        item = self.tablePrincipiante.verticalHeaderItem(1)
        item.setText(_translate("Puntajes", "2", None))
        item = self.tablePrincipiante.verticalHeaderItem(2)
        item.setText(_translate("Puntajes", "3", None))
        item = self.tablePrincipiante.verticalHeaderItem(3)
        item.setText(_translate("Puntajes", "4", None))
        item = self.tablePrincipiante.verticalHeaderItem(4)
        item.setText(_translate("Puntajes", "5", None))
        item = self.tablePrincipiante.horizontalHeaderItem(0)
        item.setText(_translate("Puntajes", "Nombre", None))
        item = self.tablePrincipiante.horizontalHeaderItem(1)
        item.setText(_translate("Puntajes", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabPrincipiante), _translate("Puntajes", "Principiante", None))
        item = self.tablePrincipiante_4.verticalHeaderItem(0)
        item.setText(_translate("Puntajes", "1", None))
        item = self.tablePrincipiante_4.verticalHeaderItem(1)
        item.setText(_translate("Puntajes", "2", None))
        item = self.tablePrincipiante_4.verticalHeaderItem(2)
        item.setText(_translate("Puntajes", "3", None))
        item = self.tablePrincipiante_4.verticalHeaderItem(3)
        item.setText(_translate("Puntajes", "4", None))
        item = self.tablePrincipiante_4.verticalHeaderItem(4)
        item.setText(_translate("Puntajes", "5", None))
        item = self.tablePrincipiante_4.horizontalHeaderItem(0)
        item.setText(_translate("Puntajes", "Nombre", None))
        item = self.tablePrincipiante_4.horizontalHeaderItem(1)
        item.setText(_translate("Puntajes", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabIntermedio), _translate("Puntajes", "Intermedio", None))
        item = self.tablePrincipiante_2.verticalHeaderItem(0)
        item.setText(_translate("Puntajes", "1", None))
        item = self.tablePrincipiante_2.verticalHeaderItem(1)
        item.setText(_translate("Puntajes", "2", None))
        item = self.tablePrincipiante_2.verticalHeaderItem(2)
        item.setText(_translate("Puntajes", "3", None))
        item = self.tablePrincipiante_2.verticalHeaderItem(3)
        item.setText(_translate("Puntajes", "4", None))
        item = self.tablePrincipiante_2.verticalHeaderItem(4)
        item.setText(_translate("Puntajes", "5", None))
        item = self.tablePrincipiante_2.horizontalHeaderItem(0)
        item.setText(_translate("Puntajes", "Nombre", None))
        item = self.tablePrincipiante_2.horizontalHeaderItem(1)
        item.setText(_translate("Puntajes", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabAvanzado), _translate("Puntajes", "Avanzado", None))
        self.btnSalir.setText(_translate("Puntajes", "Salir", None))
        self.labelMejoresTiempos.setText(_translate("Puntajes", "MEJORES TIEMPOS", None))

