# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mejorestiempos.ui'
#
# Created: Fri Jul 19 18:50:12 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MejoresTiempos(object):
    def setupUi(self, MejoresTiempos):
        MejoresTiempos.setObjectName(_fromUtf8("MejoresTiempos"))
        MejoresTiempos.resize(346, 364)
        self.tab = QtGui.QTabWidget(MejoresTiempos)
        self.tab.setGeometry(QtCore.QRect(40, 60, 261, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Broadway"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabPrincipiante = QtGui.QWidget()
        self.tabPrincipiante.setObjectName(_fromUtf8("tabPrincipiante"))
        self.tablePrincipiante = QtGui.QTableWidget(self.tabPrincipiante)
        self.tablePrincipiante.setGeometry(QtCore.QRect(20, 10, 221, 181))
        self.tablePrincipiante.setAutoScroll(False)
        self.tablePrincipiante.setObjectName(_fromUtf8("tablePrincipiante"))
        self.tablePrincipiante.setColumnCount(2)
        self.tablePrincipiante.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablePrincipiante.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabPrincipiante, _fromUtf8(""))
        self.tabIntermedio = QtGui.QWidget()
        self.tabIntermedio.setObjectName(_fromUtf8("tabIntermedio"))
        self.tableIntermedio = QtGui.QTableWidget(self.tabIntermedio)
        self.tableIntermedio.setGeometry(QtCore.QRect(20, 10, 221, 181))
        self.tableIntermedio.setAutoScroll(False)
        self.tableIntermedio.setObjectName(_fromUtf8("tableIntermedio"))
        self.tableIntermedio.setColumnCount(2)
        self.tableIntermedio.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableIntermedio.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabIntermedio, _fromUtf8(""))
        self.tabAvanzado = QtGui.QWidget()
        self.tabAvanzado.setObjectName(_fromUtf8("tabAvanzado"))
        self.tableAvanzado = QtGui.QTableWidget(self.tabAvanzado)
        self.tableAvanzado.setGeometry(QtCore.QRect(20, 10, 221, 181))
        self.tableAvanzado.setAutoScroll(False)
        self.tableAvanzado.setDragEnabled(False)
        self.tableAvanzado.setGridStyle(QtCore.Qt.SolidLine)
        self.tableAvanzado.setObjectName(_fromUtf8("tableAvanzado"))
        self.tableAvanzado.setColumnCount(2)
        self.tableAvanzado.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableAvanzado.setHorizontalHeaderItem(1, item)
        self.tab.addTab(self.tabAvanzado, _fromUtf8(""))
        self.labelMejoresTiempos = QtGui.QLabel(MejoresTiempos)
        self.labelMejoresTiempos.setGeometry(QtCore.QRect(30, 10, 281, 31))
        self.labelMejoresTiempos.setStyleSheet(_fromUtf8("font: 75 20pt \"Broadway\";"))
        self.labelMejoresTiempos.setObjectName(_fromUtf8("labelMejoresTiempos"))
        self.pushButton = QtGui.QPushButton(MejoresTiempos)
        self.pushButton.setGeometry(QtCore.QRect(130, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Broadway"))
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(MejoresTiempos)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MejoresTiempos)

    def retranslateUi(self, MejoresTiempos):
        MejoresTiempos.setWindowTitle(_translate("MejoresTiempos", "Dialog", None))
        item = self.tablePrincipiante.verticalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "1", None))
        item = self.tablePrincipiante.verticalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "2", None))
        item = self.tablePrincipiante.verticalHeaderItem(2)
        item.setText(_translate("MejoresTiempos", "3", None))
        item = self.tablePrincipiante.verticalHeaderItem(3)
        item.setText(_translate("MejoresTiempos", "4", None))
        item = self.tablePrincipiante.verticalHeaderItem(4)
        item.setText(_translate("MejoresTiempos", "5", None))
        item = self.tablePrincipiante.horizontalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "Nombre", None))
        item = self.tablePrincipiante.horizontalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabPrincipiante), _translate("MejoresTiempos", "Facil", None))
        item = self.tableIntermedio.verticalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "1", None))
        item = self.tableIntermedio.verticalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "2", None))
        item = self.tableIntermedio.verticalHeaderItem(2)
        item.setText(_translate("MejoresTiempos", "3", None))
        item = self.tableIntermedio.verticalHeaderItem(3)
        item.setText(_translate("MejoresTiempos", "4", None))
        item = self.tableIntermedio.verticalHeaderItem(4)
        item.setText(_translate("MejoresTiempos", "5", None))
        item = self.tableIntermedio.horizontalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "Nombre", None))
        item = self.tableIntermedio.horizontalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabIntermedio), _translate("MejoresTiempos", "Intermedio", None))
        self.tableAvanzado.setSortingEnabled(False)
        item = self.tableAvanzado.verticalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "1", None))
        item = self.tableAvanzado.verticalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "2", None))
        item = self.tableAvanzado.verticalHeaderItem(2)
        item.setText(_translate("MejoresTiempos", "3", None))
        item = self.tableAvanzado.verticalHeaderItem(3)
        item.setText(_translate("MejoresTiempos", "4", None))
        item = self.tableAvanzado.verticalHeaderItem(4)
        item.setText(_translate("MejoresTiempos", "5", None))
        item = self.tableAvanzado.horizontalHeaderItem(0)
        item.setText(_translate("MejoresTiempos", "Nombre", None))
        item = self.tableAvanzado.horizontalHeaderItem(1)
        item.setText(_translate("MejoresTiempos", "Tiempo", None))
        self.tab.setTabText(self.tab.indexOf(self.tabAvanzado), _translate("MejoresTiempos", "Dificil", None))
        self.labelMejoresTiempos.setText(_translate("MejoresTiempos", "MEJORES TIEMPOS", None))
        self.pushButton.setText(_translate("MejoresTiempos", "Salir", None))

